### ISSUE TITLE
Some font shapes were not available, defaults substituted.

### ISSUE THREAD

**Issue by bguetarni** [pinam45/utbm-latex-internship-report-covers#2]
While writing a report, I've found that the font used (Tahoma) does not support italic especially the command **\emph**.
Is there any way to get around this ?
Thanks.

**Comment by pinam45** [comment]
Hello, the Tahoma font does not have an italic version, on Windows if you go in `C:\Windows\Fonts\Tahoma` you can see there is only:
 - tahoma.ttf (normal)
 - tahomabd.ttf (bold)

so when [fontspec](https://ctan.org/pkg/fontspec) load the font it only generate the normal and bold versions and use the normal version for italic.

## Basic solution

Use the `FakeSlant` functionality of fontspec to slant Tahoma for the italic version like this:
```latex
\newfontfamily\italictahomafont{Tahoma}[FakeSlant=0.4]
```
and use it like that (when in Tahoma):
```latex
Hello {\italictahomafont World}!
```

## Make it easier to use

Redefine the font used by **utbmcovers** adding the `AutoFakeSlant` option to tell fontspec to automatically slant the italic version of the font like this:
```latex
\usepackage{utbmcovers}
\renewfontfamily\tahomafont{Tahoma}[AutoFakeSlant=0.4]
```
and use it like that:
```latex
Hello {\itshape World}!
Hello \textit{World}!
Hello \emph{World}!
```

## The problem

If you try the previous solution for example doing this:
```latex
\setutbmcompany{Entreprise {\emph DEMO-Contrôleurs}}
```
you will notice that it doesn't work, this is because the company name is in bold so the `\emph` select bold italic and there is a bug / strange behaviour of fontspec: `AutoSlant` slant italic but not bold italic (https://github.com/wspr/fontspec/issues/172)

The bug was reported in 2014 so I don't think it will be fixed soon...

## Final solution

Just copy the bold Tahoma font (`C:\Windows\Fonts\Tahoma\tahomabd.ttf` on Windows) in your project files and use the `FakeSlant` functionality to define a slanted version of the bold font like this:
```latex
\newfontfamily\italicboldtahomafont{tahomabd.ttf}[FakeSlant=0.4]
```
and use it like that:
```latex
\setutbmcompany{Entreprise {\italicboldtahomafont DEMO-Contrôleurs}}
```
Not the prettiest solution but at least it works.

**Comment by bguetarni** [comment]
The first solution works for me, so I go with.
Thanks a lot !
